// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/handlers.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/handlers.go -destination=internal/api/mocks/mock_auth_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/breakfront-planner/auth-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIAuthService is a mock of IAuthService interface.
type MockIAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthServiceMockRecorder
	isgomock struct{}
}

// MockIAuthServiceMockRecorder is the mock recorder for MockIAuthService.
type MockIAuthServiceMockRecorder struct {
	mock *MockIAuthService
}

// NewMockIAuthService creates a new mock instance.
func NewMockIAuthService(ctrl *gomock.Controller) *MockIAuthService {
	mock := &MockIAuthService{ctrl: ctrl}
	mock.recorder = &MockIAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthService) EXPECT() *MockIAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockIAuthService) Login(login, password string) (*models.Token, *models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", login, password)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(*models.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockIAuthServiceMockRecorder) Login(login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockIAuthService)(nil).Login), login, password)
}

// Logout mocks base method.
func (m *MockIAuthService) Logout(refreshTokenValue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", refreshTokenValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockIAuthServiceMockRecorder) Logout(refreshTokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockIAuthService)(nil).Logout), refreshTokenValue)
}

// Refresh mocks base method.
func (m *MockIAuthService) Refresh(oldRefreshTokenValue string) (*models.Token, *models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", oldRefreshTokenValue)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(*models.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockIAuthServiceMockRecorder) Refresh(oldRefreshTokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockIAuthService)(nil).Refresh), oldRefreshTokenValue)
}

// Register mocks base method.
func (m *MockIAuthService) Register(login, password string) (*models.Token, *models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", login, password)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(*models.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockIAuthServiceMockRecorder) Register(login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIAuthService)(nil).Register), login, password)
}
