// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/auth_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/auth_service.go -destination=internal/services/mocks/mock_auth_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/breakfront-planner/auth-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
	isgomock struct{}
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// CheckPassword mocks base method.
func (m *MockIUserService) CheckPassword(login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPassword", login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPassword indicates an expected call of CheckPassword.
func (mr *MockIUserServiceMockRecorder) CheckPassword(login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPassword", reflect.TypeOf((*MockIUserService)(nil).CheckPassword), login, password)
}

// CreateUser mocks base method.
func (m *MockIUserService) CreateUser(login, passHash string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", login, passHash)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserServiceMockRecorder) CreateUser(login, passHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserService)(nil).CreateUser), login, passHash)
}

// FindUser mocks base method.
func (m *MockIUserService) FindUser(arg0 *models.UserFilter) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUser", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUser indicates an expected call of FindUser.
func (mr *MockIUserServiceMockRecorder) FindUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockIUserService)(nil).FindUser), arg0)
}

// MockITokenService is a mock of ITokenService interface.
type MockITokenService struct {
	ctrl     *gomock.Controller
	recorder *MockITokenServiceMockRecorder
	isgomock struct{}
}

// MockITokenServiceMockRecorder is the mock recorder for MockITokenService.
type MockITokenServiceMockRecorder struct {
	mock *MockITokenService
}

// NewMockITokenService creates a new mock instance.
func NewMockITokenService(ctrl *gomock.Controller) *MockITokenService {
	mock := &MockITokenService{ctrl: ctrl}
	mock.recorder = &MockITokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenService) EXPECT() *MockITokenServiceMockRecorder {
	return m.recorder
}

// CreateNewTokenPair mocks base method.
func (m *MockITokenService) CreateNewTokenPair(user *models.User) (*models.Token, *models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewTokenPair", user)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(*models.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateNewTokenPair indicates an expected call of CreateNewTokenPair.
func (mr *MockITokenServiceMockRecorder) CreateNewTokenPair(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewTokenPair", reflect.TypeOf((*MockITokenService)(nil).CreateNewTokenPair), user)
}

// Refresh mocks base method.
func (m *MockITokenService) Refresh(refreshToken *models.Token, user *models.User) (*models.Token, *models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", refreshToken, user)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(*models.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockITokenServiceMockRecorder) Refresh(refreshToken, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockITokenService)(nil).Refresh), refreshToken, user)
}

// RevokeToken mocks base method.
func (m *MockITokenService) RevokeToken(token *models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockITokenServiceMockRecorder) RevokeToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockITokenService)(nil).RevokeToken), token)
}
