// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/breakfront-planner/auth-service/internal/services (interfaces: ITokenValidator)
//
// Generated by this command:
//
//	mockgen -destination=internal/services/mocks/mock_token_validator.go -package=mocks github.com/breakfront-planner/auth-service/internal/services ITokenValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/breakfront-planner/auth-service/internal/models"
	validators "github.com/breakfront-planner/auth-service/internal/validators"
	gomock "go.uber.org/mock/gomock"
)

// MockITokenValidator is a mock of ITokenValidator interface.
type MockITokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockITokenValidatorMockRecorder
	isgomock struct{}
}

// MockITokenValidatorMockRecorder is the mock recorder for MockITokenValidator.
type MockITokenValidatorMockRecorder struct {
	mock *MockITokenValidator
}

// NewMockITokenValidator creates a new mock instance.
func NewMockITokenValidator(ctrl *gomock.Controller) *MockITokenValidator {
	mock := &MockITokenValidator{ctrl: ctrl}
	mock.recorder = &MockITokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenValidator) EXPECT() *MockITokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockITokenValidator) Validate(tokenValue string, opts ...validators.ValidationOption) (*models.ParsedToken, error) {
	m.ctrl.T.Helper()
	varargs := []any{tokenValue}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Validate", varargs...)
	ret0, _ := ret[0].(*models.ParsedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockITokenValidatorMockRecorder) Validate(tokenValue any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{tokenValue}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockITokenValidator)(nil).Validate), varargs...)
}

// ValidateAccessToken mocks base method.
func (m *MockITokenValidator) ValidateAccessToken(tokenValue string) (*models.ParsedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenValue)
	ret0, _ := ret[0].(*models.ParsedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockITokenValidatorMockRecorder) ValidateAccessToken(tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockITokenValidator)(nil).ValidateAccessToken), tokenValue)
}

// ValidateRefreshToken mocks base method.
func (m *MockITokenValidator) ValidateRefreshToken(tokenValue string) (*models.ParsedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", tokenValue)
	ret0, _ := ret[0].(*models.ParsedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockITokenValidatorMockRecorder) ValidateRefreshToken(tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockITokenValidator)(nil).ValidateRefreshToken), tokenValue)
}
