// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/token_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/token_service.go -destination=internal/services/mocks/mock_token_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/breakfront-planner/auth-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockITokenRepository is a mock of ITokenRepository interface.
type MockITokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITokenRepositoryMockRecorder
	isgomock struct{}
}

// MockITokenRepositoryMockRecorder is the mock recorder for MockITokenRepository.
type MockITokenRepositoryMockRecorder struct {
	mock *MockITokenRepository
}

// NewMockITokenRepository creates a new mock instance.
func NewMockITokenRepository(ctrl *gomock.Controller) *MockITokenRepository {
	mock := &MockITokenRepository{ctrl: ctrl}
	mock.recorder = &MockITokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenRepository) EXPECT() *MockITokenRepositoryMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockITokenRepository) CheckToken(token *models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockITokenRepositoryMockRecorder) CheckToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockITokenRepository)(nil).CheckToken), token)
}

// RevokeToken mocks base method.
func (m *MockITokenRepository) RevokeToken(token *models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockITokenRepositoryMockRecorder) RevokeToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockITokenRepository)(nil).RevokeToken), token)
}

// SaveToken mocks base method.
func (m *MockITokenRepository) SaveToken(token *models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockITokenRepositoryMockRecorder) SaveToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockITokenRepository)(nil).SaveToken), token)
}

// MockIHashService is a mock of IHashService interface.
type MockIHashService struct {
	ctrl     *gomock.Controller
	recorder *MockIHashServiceMockRecorder
	isgomock struct{}
}

// MockIHashServiceMockRecorder is the mock recorder for MockIHashService.
type MockIHashServiceMockRecorder struct {
	mock *MockIHashService
}

// NewMockIHashService creates a new mock instance.
func NewMockIHashService(ctrl *gomock.Controller) *MockIHashService {
	mock := &MockIHashService{ctrl: ctrl}
	mock.recorder = &MockIHashServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHashService) EXPECT() *MockIHashServiceMockRecorder {
	return m.recorder
}

// ComparePasswords mocks base method.
func (m *MockIHashService) ComparePasswords(passHash, input string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePasswords", passHash, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComparePasswords indicates an expected call of ComparePasswords.
func (mr *MockIHashServiceMockRecorder) ComparePasswords(passHash, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePasswords", reflect.TypeOf((*MockIHashService)(nil).ComparePasswords), passHash, input)
}

// HashPassword mocks base method.
func (m *MockIHashService) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIHashServiceMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIHashService)(nil).HashPassword), password)
}

// HashToken mocks base method.
func (m *MockIHashService) HashToken(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashToken", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// HashToken indicates an expected call of HashToken.
func (mr *MockIHashServiceMockRecorder) HashToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashToken", reflect.TypeOf((*MockIHashService)(nil).HashToken), token)
}
